# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            karen ho
tagline:          # 'Web developer and analysis professional in Toronto, Ontario, Canada'
description:      'Web developer and analyst'
url:              http://karenjho.com
baseurl:

author:
  name:           'Karen Ho'
  url:            https://twitter.com/karenjho
  baseurl:        

# Custom vars
version:          3.1.2

github:
  repo:           https://github.com/poole/hyde
